---
title: "Variable names in the MSPA needs-assessment"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**`interaction_agree` = likert scale (1-5) encoding the following prompt:**

>"The LGBTQ+ community at my medical school regularly interacts (formally or informally) with the LGBTQ+ community at other medical institutions."
>
  a.	Strongly disagree (1)
  b.	Somewhat disagree (2)
  c.	Neither agree nor disagree (3) 
  d.	Somewhat agree (4) 
  e.	Strongly agree (5) 
  f.	Don’t know (NA)

**`interaction_satisfaction` = likert scale (1-5) encoding the following prompt:** 

>"I am satisfied with the degree to which the LGBTQ+ community at my medical school interacts and/or collaborates with the LGBTQ+ community at other medical institutions."
>
  a.	Strongly disagree (1)
  b.	Somewhat disagree (2)
  c.	Neither agree nor disagree (3) 
  d.	Somewhat agree (4) 
  e.	Strongly agree (5) 

**`personal_benefit_mspa` = likert scale (1-5) encoding the following prompt:**

>"I would personally benefit from an intercollegiate SGM medical student organization."
>
  a.	Strongly disagree (1)
  b.	Somewhat disagree (2)
  c.	Neither agree nor disagree (3) 
  d.	Somewhat agree (4) 
  e.	Strongly agree (5) 

**`community_benefit_mspa` = likert scale (1-5) encoding the following prompt:** 

>"The LGBTQ+ community at my medical school would benefit from an intercollegiate SGM medical student organization."
>
  a.	Strongly disagree (1)
  b.	Somewhat disagree (2)
  c.	Neither agree nor disagree (3) 
  d.	Somewhat agree (4) 
  e.	Strongly agree (5) 



